build_requires: {}
conflicts: {}
dist_name: tester.exe
distribution_type: par
dynamic_config: 0
generated_by: 'PAR::Packer version 1.025'
license: unknown
par:
  clean: 0
  signature: ''
  verbatim: 0
  version: 1.008
